- type: job
  id: STCommander
  name: job-name-spacetravel-commander
  description: job-description-spacetravel-commander
  playTimeTracker: JobSTCommander
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0 #140 hrs # Corvax-RoleTime
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
